
# This file is automatically generated, you probably don't want to edit this

FuzzyDelphiMethodOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FuzzyDelphiMethodOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            alt = "notequal",
            varEq = TRUE, ...) {

            super$initialize(
                package="FuzzyDelphiJmv",
                name="FuzzyDelphiMethod",
                requiresData=TRUE,
                ...)

            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "notequal",
                    "onegreater",
                    "twogreater"),
                default="notequal")
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)

            self$.addOption(private$..alt)
            self$.addOption(private$..varEq)
        }),
    active = list(
        alt = function() private$..alt$value,
        varEq = function() private$..varEq$value),
    private = list(
        ..alt = NA,
        ..varEq = NA)
)

FuzzyDelphiMethodResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FuzzyDelphiMethodResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fuzzy Delphi Method")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Fuzzy Delphi Method"))}))

FuzzyDelphiMethodBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FuzzyDelphiMethodBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FuzzyDelphiJmv",
                name = "FuzzyDelphiMethod",
                version = c(1,0,0),
                options = options,
                results = FuzzyDelphiMethodResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Fuzzy Delphi Method
#'
#' 
#' @param data the data as a data frame
#' @param alt .
#' @param varEq .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
FuzzyDelphiMethod <- function(
    data,
    alt = "notequal",
    varEq = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("FuzzyDelphiMethod requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- FuzzyDelphiMethodOptions$new(
        alt = alt,
        varEq = varEq)

    analysis <- FuzzyDelphiMethodClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

