
# This file is automatically generated, you probably don't want to edit this

FuzzyDelphiMethodOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FuzzyDelphiMethodOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            likertVar = "likertFive", ...) {

            super$initialize(
                package="FuzzyDelphiJmv",
                name="FuzzyDelphiMethod",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps)
            private$..likertVar <- jmvcore::OptionList$new(
                "likertVar",
                likertVar,
                options=list(
                    "likertFive",
                    "likertSeven"),
                default="likertFive")

            self$.addOption(private$..deps)
            self$.addOption(private$..likertVar)
        }),
    active = list(
        deps = function() private$..deps$value,
        likertVar = function() private$..likertVar$value),
    private = list(
        ..deps = NA,
        ..likertVar = NA)
)

FuzzyDelphiMethodResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FuzzyDelphiMethodResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        scoreTable = function() private$.items[["scoreTable"]],
        dcTable = function() private$.items[["dcTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fuzzy Delphi Method")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Fuzzy Delphi Method"))
            self$add(jmvcore::Table$new(
                options=options,
                name="scoreTable",
                title="Fuzzy Score Table",
                rows=2,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="varScore", 
                        `title`="", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dcTable",
                title="Value \"d\" Construct",
                rows=2,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="varDconstruct", 
                        `title`="Average", 
                        `type`="number"))))}))

FuzzyDelphiMethodBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FuzzyDelphiMethodBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FuzzyDelphiJmv",
                name = "FuzzyDelphiMethod",
                version = c(1,0,0),
                options = options,
                results = FuzzyDelphiMethodResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Fuzzy Delphi Method
#'
#' 
#' @param data the data as a data frame
#' @param deps the item in dataframe
#' @param likertVar .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$scoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dcTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$scoreTable$asDF}
#'
#' \code{as.data.frame(results$scoreTable)}
#'
#' @export
FuzzyDelphiMethod <- function(
    data,
    deps,
    likertVar = "likertFive") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("FuzzyDelphiMethod requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL))


    options <- FuzzyDelphiMethodOptions$new(
        deps = deps,
        likertVar = likertVar)

    analysis <- FuzzyDelphiMethodClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

